export default [
  {
    login: "nishntr",
    id: 43927448,
    node_id: "MDQ6VXNlcjQzOTI3NDQ4",
    avatar_url: "https://avatars.githubusercontent.com/u/43927448?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nishntr",
    html_url: "https://github.com/nishntr",
    followers_url: "https://api.github.com/users/nishntr/followers",
    following_url:
      "https://api.github.com/users/nishntr/following{/other_user}",
    gists_url: "https://api.github.com/users/nishntr/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nishntr/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nishntr/subscriptions",
    organizations_url: "https://api.github.com/users/nishntr/orgs",
    repos_url: "https://api.github.com/users/nishntr/repos",
    events_url: "https://api.github.com/users/nishntr/events{/privacy}",
    received_events_url: "https://api.github.com/users/nishntr/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Harshita1036",
    id: 56212299,
    node_id: "MDQ6VXNlcjU2MjEyMjk5",
    avatar_url: "https://avatars.githubusercontent.com/u/56212299?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Harshita1036",
    html_url: "https://github.com/Harshita1036",
    followers_url: "https://api.github.com/users/Harshita1036/followers",
    following_url:
      "https://api.github.com/users/Harshita1036/following{/other_user}",
    gists_url: "https://api.github.com/users/Harshita1036/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Harshita1036/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Harshita1036/subscriptions",
    organizations_url: "https://api.github.com/users/Harshita1036/orgs",
    repos_url: "https://api.github.com/users/Harshita1036/repos",
    events_url: "https://api.github.com/users/Harshita1036/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Harshita1036/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "neerukapoor",
    id: 64722224,
    node_id: "MDQ6VXNlcjY0NzIyMjI0",
    avatar_url: "https://avatars.githubusercontent.com/u/64722224?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/neerukapoor",
    html_url: "https://github.com/neerukapoor",
    followers_url: "https://api.github.com/users/neerukapoor/followers",
    following_url:
      "https://api.github.com/users/neerukapoor/following{/other_user}",
    gists_url: "https://api.github.com/users/neerukapoor/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/neerukapoor/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/neerukapoor/subscriptions",
    organizations_url: "https://api.github.com/users/neerukapoor/orgs",
    repos_url: "https://api.github.com/users/neerukapoor/repos",
    events_url: "https://api.github.com/users/neerukapoor/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/neerukapoor/received_events",
    type: "User",
    site_admin: false,
  },
];
