export default {
  login: "Prateek272000",
  id: 56107997,
  node_id: "MDQ6VXNlcjU2MTA3OTk3",
  avatar_url: "https://avatars.githubusercontent.com/u/56107997?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Prateek272000",
  html_url: "https://github.com/Prateek272000",
  followers_url: "https://api.github.com/users/Prateek272000/followers",
  following_url:
    "https://api.github.com/users/Prateek272000/following{/other_user}",
  gists_url: "https://api.github.com/users/Prateek272000/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Prateek272000/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Prateek272000/subscriptions",
  organizations_url: "https://api.github.com/users/Prateek272000/orgs",
  repos_url: "https://api.github.com/users/Prateek272000/repos",
  events_url: "https://api.github.com/users/Prateek272000/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Prateek272000/received_events",
  type: "User",
  site_admin: false,
  name: "Prateek Sharma",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 19,
  public_gists: 0,
  followers: 3,
  following: 3,
  created_at: "2019-10-03T07:08:38Z",
  updated_at: "2021-06-20T09:08:34Z",
};
